require("lcc.basic")
require("lcc.env")
require("lcc.plugins.theme")
require("lcc.plugins.lsp")
require("lcc.plugins.mini")
require("lcc.plugins.treesitter")
require("lcc.plugins.scroll")
require("lcc.plugins.marks")
require("lcc.plugins.undotree")
require("lcc.plugins.conform")
local wezterm = require("lcc.wezterm")
wezterm.setup()
local sublime = require("lcc.sublime")
sublime.setup()
-- apply_sublime_mode()
require("lcc.mouseEv") 
