cat > temp_s.txt <<PASEOF
CONFIG_VLAN_8021Q=y
CONFIG_LLC=y
CONFIG_STP=y
CONFIG_NAMESPACES=y
CONFIG_UTS_NS=y
CONFIG_IPC_NS=y
CONFIG_USER_NS=y
CONFIG_PID_NS=y
CONFIG_NET_NS=y
CONFIG_CGROUPS=y
CONFIG_CGROUP_FREEZER=y
CONFIG_CGROUP_PIDS=y
CONFIG_CGROUP_DEVICE=y
CONFIG_CGROUP_CPUACCT=y
CONFIG_CGROUP_HUGETLB=y
CONFIG_CGROUP_PERF=y
CONFIG_CGROUP_SCHED=y
CONFIG_CGROUP_MEMCG=y
CONFIG_CGROUP_MEMCG_SWAP=y
CONFIG_EFI_PARTITION=y
CONFIG_ZLIB_DEFLATE=y
CONFIG_ZLIB_INFLATE=y
CONFIG_VIRTUALIZATION=y
CONFIG_KVM=y
CONFIG_KVM_INTEL=y
CONFIG_KVM_AMD=y
CONFIG_CGROUP_NS=y
CONFIG_CGROUP_BPF=y
CONFIG_MEMCG=y
CONFIG_MEMCG_SWAP=y
CONFIG_FUSE_FS=y
CONFIG_TMPFS=y
CONFIG_TMPFS_POSIX_ACL=y
CONFIG_VFS_CAP_DATA=y
CONFIG_VHOST_NET=y
CONFIG_BRIDGE=y
CONFIG_BLK_CGROUP=y
CONFIG_OVERLAY_FS=y
CONFIG_SUNRPC=y
CONFIG_NFS_FS=y
CONFIG_NFS_V3=y
CONFIG_NFS_V4=y
CONFIG_ZLIB_DEFLATE=y
CONFIG_ZLIB_INFLATE=y
CONFIG_LIBCRC32C=y
CONFIG_SOFT_WATCHDOG=y
CONFIG_BRIDGE_NETFILTER=y
CONFIG_NETFILTER_FAMILY_BRIDGE=y
CONFIG_SKB_EXTENSIONS=y
CONFIG_NET_CLS_ACT=y
CONFIG_NET_SCH_HTB=y
CONFIG_NET_SCH_INGRESS=y
CONFIG_VETH=y
CONFIG_MACVLAN=y
CONFIG_TUN=y
CONFIG_CGROUP_WRITEBACK=y
CONFIG_CPUSETS=y
CONFIG_CRYPTO_SHA256=y
CONFIG_CRYPTO_SHA512=y
CONFIG_BLK_DEV_LOOP=y
CONFIG_WATCHDOG_NOWAYOUT=y
CONFIG_VIRTIO_NET=y
CONFIG_VIRTIO_BLK=y
CONFIG_NETFILTER_XT_TARGET_MASQUERADE=y
CONFIG_NETFILTER_XT_MATCH_ADDRTYPE=y
CONFIG_NETFILTER_XT_MATCH_IPVS=y
CONFIG_NETFILTER_XT_MATCH_COMMENT=y
CONFIG_IP_VS=y
CONFIG_BLK_DEV_THROTTLING=y
CONFIG_IKCONFIG=y
CONFIG_IKCONFIG_PROC=y
# 防火牆核心支持
CONFIG_NETFILTER=y
CONFIG_NETFILTER_ADVANCED=y
CONFIG_NF_CONNTRACK=y
CONFIG_NF_CONNTRACK_PROCFS=y
CONFIG_NF_CONNTRACK_EVENTS=y
CONFIG_NF_CT_PROTO_TCP=y
CONFIG_NF_CT_PROTO_UDP=y
CONFIG_NF_CT_PROTO_ICMP=y
CONFIG_NF_TABLES=y
CONFIG_NF_TABLES_INET=y
# 這是你剛才抓到的「導航儀」，負責確認回包路徑
CONFIG_NFT_FIB_IPV4=y
# 這是讓 nftables 能處理「介面 Meta 資訊」的基礎 (例如判斷 iifname)
CONFIG_NFT_META=y
# 這是核心在做 NAT 之前，處理封包分片重組的必要零件
CONFIG_NF_DEFRAG_IPV4=y
CONFIG_NFT_CT=y
CONFIG_NFT_NAT=y
CONFIG_NFT_MASQ=y
CONFIG_NF_NAT=y
# --- 讓 iptables 指令不報錯的相容層 (這能解決 TRACE 報錯) ---
CONFIG_NETFILTER_XTABLES=y
CONFIG_NETFILTER_XT_TARGET_TRACE=y
CONFIG_NFT_COMPAT=y
# PVE 防火牆必備：完整的 Netfilter 支援
CONFIG_NETFILTER_XT_TARGET_REJECT=y
CONFIG_NETFILTER_XT_MATCH_BPF=y
CONFIG_NETFILTER_XT_MATCH_CONNLIMIT=y
CONFIG_NETFILTER_XT_MATCH_CONNTRACK=y
CONFIG_NETFILTER_XT_MATCH_STATE=y
# 具體的 iptables 支援 (PVE 強烈依賴)
CONFIG_IP_NF_IPTABLES=y
CONFIG_IP_NF_FILTER=y
CONFIG_IP_NF_TARGET_REJECT=y
CONFIG_IP_NF_MANGLE=y
CONFIG_IP_NF_RAW=y
# NFT 規則功能擴展
CONFIG_NFT_LIMIT=y
CONFIG_NFT_LOG=y
CONFIG_NFT_REJECT=y

# --- 讓核心「看懂」IPv4 流量的關鍵 (你目前缺這個) ---
CONFIG_NF_TABLES_IPV4=y
CONFIG_NFT_CHAIN_NAT_IPV4=y
CONFIG_NF_NAT_IPV4=y
CONFIG_NFT_BRIDGE_META=y
CONFIG_NFT_BRIDGE_REJECT=y

# 確保 NAT 變裝的核心邏輯
CONFIG_NF_NAT_MASQUERADE=y

CONFIG_NF_CONNTRACK_FTP=y
CONFIG_NF_CONNTRACK_TFTP=y
CONFIG_NF_NAT_FTP=y
CONFIG_NF_CONNTRACK_BRIDGE=y
CONFIG_NF_TABLES_BRIDGE=y
CONFIG_NFT_CHAIN_FORWARD_IPV4=y
CONFIG_NF_TABLES_ARP=y
EOF
PASEOF


#sed -e '/^EOF/r temp_s.txt' -e '/^EOF/a EOF' -e '/^EOF/d' zfs-on-wsl.sh > zfs-on-wsl-pve.sh && rm temp_s.txt
sed -e '/^EOF/r temp_s.txt' -e '/^EOF/d' -e 's/modules_install/modules_install INSTALL_MOD_STRIP=1/' zfs-on-wsl.sh > zfs-on-wsl-pve.sh && rm temp_s.txt

cat >> zfs-on-wsl-pve.sh << 'PVEEOF'
mv "/mnt/c/ZFSonWSL/bzImage-new" "/mnt/c/ZFSonWSL/bzImage-${UPSTREAMKERNELVER}"
VER=$(curl -s https://api.github.com/repos/microsoft/WSL2-Linux-Kernel/releases/latest | grep -oP '"tag_name": ".+-\K(.*)(?=")')
REAL_VER=$(ls /lib/modules | grep "^${VER}" | head -n 1)
CMD="tar -czf /mnt/c/ZFSonWSL/module-${REAL_VER}.tgz -C /lib/modules ${REAL_VER}"
echo $CMD
sudo $CMD
PVEEOF


chmod +x zfs-on-wsl-pve.sh

